name: Verify Formatting and Lint
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Verify Formatting and Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm ci
      - name: Prettier
        run: npm run format
      - name: Lint
        run: npm run lint
